### ISSUE TITLE
运行node index.js,报错

### ISSUE THREAD

**Issue by PetersonLian** [feit/WeixinBot#14]
Error: Cannot find module 'babel-runtime/core-js/get-iterator'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\wx-bot\node_modules\weixinbot\lib\weixinbot.js:3:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by foxtail000** [comment]
同上。 已经不维护了吗

**Comment by zwlcoding** [comment]
在项目中安装依赖模块
npm install babel-core babel-loader --save-dev

添加 .babelrc 文件
{ 
    "presets" : ["es2015", "react"]
}
